# handles application dependencies and virtual env

- name: ensure pip and venv are installed
  apt:
    name: ['python3-venv', 'python3-pip']
    update_cache: yes
  become: yes


- name: check if virtualenv is created
  stat:
    path: "{{ venv_dir }}"
  register: venv_created


- name: create virtualenv if it doesnt
  shell: "python3 -m venv {{ venv_dir }}"
  when: not venv_created.stat.exists


- name: use pip3 to install application dependencies
  shell: "cd {{ app_dir }}; {{ venv_dir }}/bin/pip3 install --upgrade -r requirements.txt"
